# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
    ]
