# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20170225_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_articles', to='accounts.UserProfile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_comments', to='accounts.UserProfile'),
        ),
    ]
